---
- name: Verify if Homebrew is installed
  command: which brew
  register: brew_check
  ignore_errors: true

- name: Install Homebrew if not installed
  shell: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
  when: brew_check.rc != 0

- name: "stripping ansible from path"
  set_fact:
    current_path: "{{ ansible_env.PWD }}"

- name: "stripped path"
  set_fact:
    stripped_path: "{{ current_path | regex_replace('/ansible$', '') }}"

- name: Install packages from Brewfile via brew bundle
  command: brew bundle --file=Brewfile
  args:
    chdir: "{{ stripped_path }}"
