---
- name: "stripping ansible from path"
  set_fact:
    current_path: "{{ ansible_env.PWD }}"

- name: "stripped path"
  set_fact:
    stripped_path: "{{ current_path | regex_replace('/ansible$', '') }}"

- name: Ensure required packages are installed (MacOS)
  include_tasks: darwin.yml
  when: ansible_os_family == "Darwin"
  tags:
    - darwin
    - macos
    - osx
