vim.g.mapleader = ' '

require('impatient')
require 'seb_config.plugins'
require 'seb_config.tmux'
require 'seb_config.treesitter'
require 'seb_config.telescope'
require 'seb_config.comment'
require 'seb_config.signs'
require 'seb_config.lsp'
require 'seb_config.nullls'
require 'seb_config.completion'
require 'seb_config.snip'
require 'seb_config.statusline'
require 'seb_config.filetypes'
require 'seb_config.formatter'
require 'seb_config.autopairs'
require 'seb_config.bufferline'
require 'seb_config.nvimtree'
require 'seb_config.nvim-clip'
require 'seb_config.indent'
require 'seb_config.colorscheme'
require 'seb_config.mappings'
require 'seb_config.which-key'
require 'seb_config.go'
