return {
  cmd = { "yaml-language-server", "--stdio" },
  filetypes = { "yaml", "yaml.docker-compose", "yaml.gitlab", "yaml.helm-values" },
  root_markers = { ".git" },
  single_file_support = true,
  settings = {
    yaml = {
      format = {
        enabled = true,
      },
      schemas = {
        ["https://json.schemastore.org/github-workflow.json"] = "/.github/workflows/*",
        ["https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json"] = "/docker-compose.yml",
        ["https://goreleaser.com/static/schema.json"] = "/.goreleaser.yml",
        ["https://json.schemastore.org/golangci-lint.json"] = {
          "/.golangci.yml",
          "/.golangci.yaml",
        },
        ["https://json.schemastore.org/chart.json"] = { "/Chart.yml", "/Chart.yaml" },
        -- ["kubernetes"] = "/*",
        ["/Users/sebastienledigabel/temp/catalog-schema.json"] = { "/.catalog.yml" },
      },
      hover = true,
      completion = true,

      customTags = {
        "!fn",
        "!And",
        "!And sequence",
        "!If",
        "!If sequence",
        "!Not",
        "!Not sequence",
        "!Equals",
        "!Equals sequence",
        "!Or",
        "!Or sequence",
        "!FindInMap",
        "!FindInMap sequence",
        "!Base64",
        "!Join",
        "!Join sequence",
        "!Cidr",
        "!Ref",
        "!Sub",
        "!Sub sequence",
        "!GetAtt",
        "!GetAZs",
        "!ImportValue",
        "!ImportValue sequence",
        "!Select",
        "!Select sequence",
        "!Split",
        "!Split sequence",
      },
    },
  },
}
